services:
  postgres:
    image: postgres:16-alpine
    container_name: as_transports_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: as_transports
    ports:
      - "5432:5432"
    volumes:
      - as_transports_postgres_data:/var/lib/postgresql/data

volumes:
  as_transports_postgres_data: